Repository boyter/scc, pull requests merged in 2024-11, with the labels that each got.

#554 typo fix
  SCC-OUTPUT-REPORT.html
  processor/workers.go
Labels: M/complexity, S/size

#557 Add in support for up
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/up.up
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/complexity, XL/size

#558 Fix TestSimpleCache_Multiple
  cmd/badges/simplecache_test.go
Labels: M/complexity, XS/size

#556 Use json-iterator/go for all JSON operations
  SCC-OUTPUT-REPORT.html
  cmd/badges/main.go
  processor/formatters.go
  scripts/include.go
Labels: M/size, M/complexity

#559 Add support for emit https://esolangs.org/wiki/EmiT
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/emit.emit
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/complexity, XL/size

#561 Add a newline to output files
  SCC-OUTPUT-REPORT.html
  processor/formatters.go
  processor/formatters_test.go
Labels: M/size, M/complexity

#562 Add metal language support
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/metal.metal
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/complexity, XL/size
