Repository boyter/scc, pull requests merged in 2025-04, with the labels that each got.

#600 add Tact language
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/tact.tact
  languages.json
  processor/constants.go
Labels: M/size, M/complexity

#594 Accelerating scc startup speed with code generation
  SCC-OUTPUT-REPORT.html
  processor/constants.go
  processor/processor.go
  scripts/include.go
  scripts/languages.tmpl
  test-all.sh
Labels: XL/size, VH/complexity

#602 Add in support for C3 lang
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/c3.c3
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity

#603 add language scallop
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/scallop.scl
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity

#607 Add OpenTofu
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/test.tofu
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity

#608 Silent some CodeFactor issues
  benchmark.sh
  cmd/badges/example.py
Labels: S/size, L/complexity

#609 Support xmake & update lua and luau
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/lua.lua
  examples/language/luau.luau
  examples/language/xmake.lua
  languages.json
  processor/constants.go
  processor/detector.go
  processor/detector_test.go
  test-all.sh
Labels: XL/size, VH/complexity
