Repository boyter/scc, pull requests merged in 2025-06, with the labels that each got.

#619 RAML support
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/raml.raml
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity

#621 feat: Support .Net 10 CSharp shebang
  SCC-OUTPUT-REPORT.html
  languages.json
  processor/constants.go
Labels: S/size, VL/complexity

#622 feat: format numbers using current locale
  README.md
  processor/formatters.go
Labels: XL/size, VL/complexity

#623 doc: missing new formatting delivered in #335
  README.md
Labels: S/size, VL/complexity

#624 feat: speed up specific languages test
  SCC-OUTPUT-REPORT.html
  test-all.sh
Labels: S/size, L/complexity

#625 Refactor: simplify printXXX functions usages
  SCC-OUTPUT-REPORT.html
  processor/detector.go
  processor/file.go
  processor/formatters.go
  processor/formatters_test.go
  processor/processor.go
  processor/trace.go
  processor/trace_test.go
  processor/workers.go
Labels: XL/size, VH/complexity

#626 fix: fix CountStats performance
  SCC-OUTPUT-REPORT.html
  processor/workers.go
Labels: M/size, M/complexity

#629 Docs: Fix typo in 'scc for Teams & Enterprise' section of README.md
  README.md
Labels: S/size, VL/complexity
