Repository boyter/scc, pull requests merged in 2025-05, with the labels that each got.

#612 Fix line comment count for nix (#611)
  languages.json
  processor/constants.go
Labels: M/size, M/complexity

#613 fix TypeScript and JavaScript language information
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/issue610/issue610.ts
  examples/language/javascript.js
  examples/language/typescript.ts
  languages.json
  processor/constants.go
  test-all.sh
Labels: L/complexity, L/size

#614 Support PostScript
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/PostScript.ps
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, L/complexity

#615 update Perl and Python language information
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/perl.pl
  examples/language/python.py
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, M/complexity

#616 Support GTK Blueprint
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/Blueprint.blp
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity

#617 Support new language Go+
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/goplus.gop
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity
