Repository boyter/scc, pull requests merged in 2025-01, with the labels that each got.

#569 add wise jobfile definition
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  languages.json
  processor/constants.go
Labels: M/complexity, S/size

#570 Use a faster method to convert ints to strings
  SCC-OUTPUT-REPORT.html
  cmd/badges/simplecache_test.go
  processor/formatters.go
Labels: M/size, M/complexity

#571 Add Treetop Support - https://cjheath.github.io/treetop/
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  languages.json
  processor/constants.go
Labels: M/size, M/complexity

#572 Make "--exclude-dir" support multi-level dirs
  examples/issue564/a/level1/level2/test.py
  examples/issue564/b/c/level2/test.py
  examples/issue564/level1/level2/test.py
  examples/issue564/level1/test.go
  examples/issue564/test.go
  go.mod
  go.sum
  test-all.sh
  vendor/github.com/boyter/gocodewalker/Makefile
  vendor/github.com/boyter/gocodewalker/check.sh
  vendor/github.com/boyter/gocodewalker/dir_suffix.go
  vendor/github.com/boyter/gocodewalker/file.go
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/modules.txt
Labels: M/complexity, XL/size

#573 Convert to simplecache
  SCC-OUTPUT-REPORT.html
  cmd/badges/main.go
  cmd/badges/simplecache.go
  cmd/badges/simplecache_test.go
  go.mod
  go.sum
  vendor/github.com/boyter/simplecache/.gitignore
  vendor/github.com/boyter/simplecache/LICENSE
  vendor/github.com/boyter/simplecache/README.md
  vendor/github.com/boyter/simplecache/simplecache.go
  vendor/modules.txt
Labels: M/complexity, XL/size
