Repository boyter/scc, pull requests merged in 2025-02, with the labels that each got.

#579 Fix docker image name
  README.md
Labels: M/complexity, S/size

#586 (docs) fix GitLab CI link to metrics reports
  README.md
Labels: M/complexity, S/size

#587 Update zig complexity checks
  SCC-OUTPUT-REPORT.html
  examples/language/zig.zig
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, M/complexity

#592 Add fedora install instructions in README
  README.md
Labels: S/size, VL/complexity

#588 Upgrade to Go 1.24
  Dockerfile
  README.md
  go.mod
  go.sum
  processor/formatters.go
  processor/processor.go
  processor/workers.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: M/size, M/complexity

#591 start to add in more stats
  SCC-OUTPUT-REPORT.html
  processor/structs.go
  processor/workers.go
  processor/workers_regression_test.go
Labels: M/size, M/complexity

#593 add in HCL support
  LANGUAGES.md
  SCC-OUTPUT-REPORT.html
  examples/language/hcl.hcl
  languages.json
  processor/constants.go
  test-all.sh
Labels: M/size, VL/complexity
